set(ROOT "${SOURCE_ROOT}")
file(GLOB_RECURSE PUBLIC_HEADERS "${ROOT}/include/quickapp/lvgl/mount/*.h")
foreach(FILE_PATH IN LISTS PUBLIC_HEADERS)
  file(READ "${FILE_PATH}" CONTENT)
  foreach(FORBIDDEN IN ITEMS "lvgl.h" "SDL.h" "uv.h" "RuntimeTreeStore" "Revision")
    string(FIND "${CONTENT}" "${FORBIDDEN}" POSITION)
    if(NOT POSITION EQUAL -1)
      message(FATAL_ERROR "LV-S04 public header leaks ${FORBIDDEN}: ${FILE_PATH}")
    endif()
  endforeach()
endforeach()
message(STATUS "LV-S04 public boundary scan passed")
